Error component
scientist-softserv/webstore-component-library pull request #122
Opened 2023-01-17 23:01 UTC by summer-cook

2023-01-20 15:25 UTC, alishaevn requested changes

2023-01-20 15:25 UTC, alishaevn commented on src/components/Error/Error.jsx
> +        {errorText && (errorText)}
if `errorText` is required, why are we checking for its existence?

2023-01-20 15:25 UTC, alishaevn commented on src/components/Error/Error.jsx
> +  return (
we can do an implicit return here.

2023-01-20 15:25 UTC, alishaevn commented on src/components/Error/Error.jsx
> +            Click to return to the previous page.
an error redirects the user to a new page?

2023-01-20 20:10 UTC, alishaevn requested changes

2023-01-20 20:10 UTC, alishaevn commented on src/components/Error/Error.jsx
> +  const { errorTitle, errorText, variant} = errors
```suggestion
  const { errorTitle, errorText, variant } = errors
```

2023-01-20 22:23 UTC, labradford approved these changes

2023-01-23 14:37 UTC, alishaevn requested changes

2023-01-23 14:37 UTC, alishaevn commented on src/components/Error/Error.jsx
> +  const [show, setShow] = useState(true)
```suggestion
  const [show, setShow] = useState(true)

```

2023-01-23 14:38 UTC, alishaevn approved these changes

2023-01-23 15:00 UTC, merged