200 make click boxes new
scientist-softserv/webstore-component-library pull request #203
Opened 2024-02-01 00:43 UTC by AragonJ13

Co-authored by:Dalton McAuliffe[[dalton.j.mcauliffe97@gmail.com]
Co-authored by:Adrian Carranza[[adriancarranza0113@gmail.com]
Ref: #200

Description
currently, it is not obvious that the featured service links on the homepage are links. the goal is to improve the user experience by making the entire card clickable instead of just the title

User Impact
Users will be able to click the whole car to a new request instead of only clinking the title.

Instructions
go to website home page click on cards on the homepage and cards will take you to the desired request

2024-02-01 18:12 UTC, summer-cook commented on src/compounds/Item/Item.jsx
> +              className={`cover ${orientation === 'horizontal' ? 'img-fluid h-100 rounded-start' : 'card-img-top'}`}
Indent lines 60-62 one more time

2024-02-02 00:50 UTC, alishaevn requested changes

2024-02-02 00:50 UTC, alishaevn commented on src/components/NextLink/NextLink.jsx
> +  ]).isRequired,
👍🏾

2024-02-02 00:50 UTC, alishaevn commented on src/compounds/Item/Item.jsx
> +              alt={alt}
```suggestion
                className={`cover ${orientation === 'horizontal' ? 'img-fluid h-100 rounded-start' : 'card-img-top'}`}
                src={src}
                alt={alt}
```

2024-02-02 00:50 UTC, alishaevn approved these changes

2024-02-02 00:50 UTC, merged